spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb?currentSchema=company
    username: db_user
    password: user123

    jpa:
      hibernate:
        ddl-auto: create
        properties:
          hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect